media-user-token: "Ai2cINdh/Tzu3+OvnY8tbXY41QyK5gEWEuMMxBn/7gZvQPeX5jjVEW5hxh0ZBt+ou+IFPoyWWpy4JNxBdIg4jNqGV122iH3epe7wzj2E0ZaKj2fNwYiCajxRuXgA7wOcWz3RBIHEQthY7LTNzB6rlaP5kKwbhv7/FohGCOEbOaA/krvhdr2SpZMl9nVpw/LG1/sOj8yGOfbGkU+hUCpwqAZXbd/PXj9pjaJ8F5mjTeCIvdLOCg==" #If you need to obtain the lyrics, need to change it
authorization-token: "AAAAAAAAAAKjxkKobZEkQODPyNFkZpf+tJAThSJgNnJdhlvxAWyLMQl25bb4AVcZBpRBoM2XkjKZtW8/z3QtRB/UyjMlDvLcTeFsIhixW+Lr7mfdt3nzMx9rmfB5Gvx8v6SHiRObWgCxnEUE7dMSbsu9kSfINkxizwuf6KCZr/fz1dWEMXI0fxKEfpAoHVFXTGBYdBFd1Q9/ZhMiwMWIAjji2tjxJTWcWC6Av7c9JPVi4nwz8mZPiq/jansgMhKbdxgXL1ifQlD5SI+fCYHy0vMH2NV5/Z8a4f7EvppNPNhf2GgylZDtUA==" #You don't need to change it; it can automatically obtain token
language: ""         #supportedLanguage by each storefront --> https://gist.github.com/itouakirai/c8ba9df9dc65bd300094103b058731d0
lrc-type: "lyrics"   #lyrics or syllable-lyrics
lrc-format: "lrc"   #lrc or ttml
embed-lrc: true     #Unable to embed ttml lyrics
save-lrc-file: false
save-artist-cover: false
save-animated-artwork: false    # If enabled, requires ffmpeg
emby-animated-artwork: false    # If enabled, requires ffmpeg
embed-cover: true
cover-size: 5000x5000
cover-format: jpg       #jpg png or original
alac-save-folder: AM-DL downloads
atmos-save-folder: AM-DL-Atmos downloads
check: "" # API or .txt
force-api: false
decrypt-m3u8-port: "127.0.0.1:10020"
get-m3u8-port: "127.0.0.1:20020"
get-m3u8-from-device: true
#set 'all' to retrieve all m3u8, and set 'hires' to only detect hires m3u8.
get-m3u8-mode: hires # all hires
alac-max: 192000  #192000 96000 48000 44100
atmos-max: 2768  #2768 2448
limit-max: 200
#{AlbumId} {AlbumName} {ArtistName} {ReleaseDate} {ReleaseYear} {UPC} {Copyright} {Quality} {Codec} {Tag} {RecordLabel}
#example: {ReleaseYear} - {ArtistName} - {AlbumName}({AlbumId})({UPC})({Copyright}){Codec}
album-folder-format: "{AlbumName}"
#{PlaylistId} {PlaylistName} {ArtistName} {Quality} {Codec} {Tag}
playlist-folder-format: "{PlaylistName}"
#{SongId} {SongNumer} {SongName} {DiscNumber} {TrackNumber} {Quality} {Codec} {Tag}
#example: Disk {DiscNumber} - Track {TrackNumber} {SongName} [{Quality}]{{Tag}}"
song-file-format: "{SongNumer}. {SongName}"
#{ArtistId} {ArtistName}/{UrlArtistName}
#if artist-folder-format set "",will not make artist folder
artist-folder-format: "{ArtistName}"
#if set "" will not add tag
explicit-choice : "[E]"
clean-choice : "[C]"
apple-master-choice : "[M]"
#if set true,for playlst,will use songinfo for meta #albumname track disk
use-songinfo-for-playlist: false
#if set true,will download album cover for playlist
dl-albumcover-for-playlist: false
